### ISSUE TITLE
Feature Request: Dividers.

### ISSUE THREAD

**Issue by ostapch** [timoschwarzer/TelegramDesktopThemeGenerator#1]
Can you provide dividers in contact list?

**Comment by timoschwarzer** [comment]
Hello there!
Unfortunately, I can't add any features to Telegram Desktop. This script only generates the theme files and therefore you can only use the theming features that are supported by Telegram Desktop. You can open an issure [here](https://github.com/telegramdesktop/tdesktop) if you want a particular (theming) feature.
